name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: "Check app"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      # Setup and dependencies
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Setup Biome CLI
        uses: biomejs/setup-biome@29711cbb52afee00eb13aeb30636592f9edc0088 # v2
      - name: Run Biome
        run: biome ci
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version-file: ".node-version"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Sync astro types
        run: pnpm astro sync
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
      - name: Lint
        run: pnpm lint
      - name: Check types
        run: pnpm check
      - name: Format
        run: pnpm format:check
